name: Update

on:
  push:
    paths:
      - '.github/workflows/update.yml'
      - 'scripts/*.ts'
      - 'examples/example.js'
      - 'src/methods/**'
      - 'src/constants.ts'
      - 'src/utils.ts'
    branches:
      - 'master'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Update example
        run: yarn example
        env:
          UBI_EMAIL: ${{ secrets.UBI_EMAIL }}
          UBI_PASSWORD: ${{ secrets.UBI_PASSWORD }}

      - name: Update method responses
        run: yarn methods
        env:
          UBI_EMAIL: ${{ secrets.UBI_EMAIL }}
          UBI_PASSWORD: ${{ secrets.UBI_PASSWORD }}

      - name: Update tables
        run: yarn tables

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: '[auto] chore: update example, method responses and tables'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
