name: Update documentation files

on:
  push:
    paths:
    - 'lib/methods/getStats.js'
    - 'lib/constants.js'
    - 'scripts/**'
    branches: master
  pull_request:
    paths:
    - 'lib/methods/getStats.js'
    - 'lib/constants.js'
    - 'scripts/**'

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Set up Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install dependencies
      run: npm install
    - name: Regenerate definition files
      run: npm run types
    - name: Commit TypeScript changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "[auto] Update typings"
        add: typings
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update full response file
      run: npm run response
      env:
        UBI_EMAIL: ${{ secrets.UBI_EMAIL }}
        UBI_PASSWORD: ${{ secrets.UBI_PASSWORD }}
    - name: Commit response changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "[auto] Update response file"
        add: doc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
